//
// Generated by Microsoft (R) HLSL Shader Compiler 10.1
//
//
// Buffer Definitions: 
//
// cbuffer PointLightCBuf
// {
//
//   float3 viewLightPos;               // Offset:    0 Size:    12
//   float3 ambient;                    // Offset:   16 Size:    12
//   float3 diffuseColor;               // Offset:   32 Size:    12
//   float diffuseIntensity;            // Offset:   44 Size:     4
//   float attConst;                    // Offset:   48 Size:     4
//   float attLin;                      // Offset:   52 Size:     4
//   float attQuad;                     // Offset:   56 Size:     4
//
// }
//
// cbuffer ObjectCBuf
// {
//
//   bool useGlossAlpha;                // Offset:    0 Size:     4
//   bool useSpecularMap;               // Offset:    4 Size:     4
//   float3 specularColor;              // Offset:   16 Size:    12
//   float specularWeight;              // Offset:   28 Size:     4
//   float specularGloss;               // Offset:   32 Size:     4
//
// }
//
//
// Resource Bindings:
//
// Name                                 Type  Format         Dim      HLSL Bind  Count
// ------------------------------ ---------- ------- ----------- -------------- ------
// splr                              sampler      NA          NA             s0      1 
// tex                               texture  float4          2d             t0      1 
// spec                              texture  float4          2d             t1      1 
// PointLightCBuf                    cbuffer      NA          NA            cb0      1 
// ObjectCBuf                        cbuffer      NA          NA            cb1      1 
//
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// Position                 0   xyz         0     NONE   float   xyz 
// Normal                   0   xyz         1     NONE   float   xyz 
// Texcoord                 0   xy          2     NONE   float   xy  
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_Target                0   xyzw        0   TARGET   float   xyzw
//
ps_5_0
dcl_globalFlags refactoringAllowed | skipOptimization
dcl_constantbuffer CB0[4], immediateIndexed
dcl_constantbuffer CB1[3], immediateIndexed
dcl_sampler s0, mode_default
dcl_resource_texture2d (float,float,float,float) t0
dcl_resource_texture2d (float,float,float,float) t1
dcl_input_ps linear v0.xyz
dcl_input_ps linear v1.xyz
dcl_input_ps linear v2.xy
dcl_output o0.xyzw
dcl_temps 5
//
// Initial variable locations:
//   v0.x <- viewFragPos.x; v0.y <- viewFragPos.y; v0.z <- viewFragPos.z; 
//   v1.x <- viewNormal.x; v1.y <- viewNormal.y; v1.z <- viewNormal.z; 
//   v2.x <- tc.x; v2.y <- tc.y; 
//   o0.x <- <main return value>.x; o0.y <- <main return value>.y; o0.z <- <main return value>.z; o0.w <- <main return value>.w
//
#line 24 "F:\MyRepo\DirectXRenderer\Sandbox\asset\shader\PhongDifSpc_PS.hlsl"
dp3 r0.x, v1.xyzx, v1.xyzx
rsq r0.x, r0.x
mul r0.xyz, r0.xxxx, v1.xyzx  // r0.x <- viewNormal.x; r0.y <- viewNormal.y; r0.z <- viewNormal.z

#line 26
nop 

#line 11 "F:\MyRepo\DirectXRenderer\Sandbox\asset\shader\Common\LightVectorData.hlsli"
mov r1.xyz, -v0.xyzx
add r1.xyz, r1.xyzx, cb0[0].xyzx  // r1.x <- lv.vToL.x; r1.y <- lv.vToL.y; r1.z <- lv.vToL.z

#line 12
dp3 r0.w, r1.xyzx, r1.xyzx
sqrt r0.w, r0.w  // r0.w <- lv.distToL

#line 13
div r2.xyz, r1.xyzx, r0.wwww  // r2.x <- lv.dirToL.x; r2.y <- lv.dirToL.y; r2.z <- lv.dirToL.z

#line 28 "F:\MyRepo\DirectXRenderer\Sandbox\asset\shader\PhongDifSpc_PS.hlsl"
mov r1.w, cb1[2].x  // r1.w <- specularPowerLoaded

#line 29
sample_indexable(texture2d)(float,float,float,float) r3.xyzw, v2.xyxx, t1.xyzw, s0  // r3.x <- specularSample.x; r3.y <- specularSample.y; r3.z <- specularSample.z; r3.w <- specularSample.w

#line 31
ine r2.w, l(0, 0, 0, 0), cb1[0].y
if_nz r2.w

#line 33
  mov r3.xyz, r3.xyzx  // r3.x <- specularReflectionColor.x; r3.y <- specularReflectionColor.y; r3.z <- specularReflectionColor.z

#line 34
else 

#line 37
  mov r3.xyz, cb1[1].xyzx  // r3.x <- specularReflectionColor.x; r3.y <- specularReflectionColor.y; r3.z <- specularReflectionColor.z

#line 38
endif 

#line 39
ine r2.w, l(0, 0, 0, 0), cb1[0].x
if_nz r2.w

#line 41
  mul r2.w, r3.w, l(13.000000)
  log r3.w, l(2.000000)
  mul r2.w, r2.w, r3.w
  exp r1.w, r2.w

#line 42
endif 

#line 44
nop 
mov r2.w, cb0[3].x
mov r3.w, cb0[3].y
mov r4.x, cb0[3].z

#line 20 "F:\MyRepo\DirectXRenderer\Sandbox\asset\shader\Common\ShaderOps.hlsli"
mul r3.w, r0.w, r3.w
add r2.w, r2.w, r3.w
mul r0.w, r0.w, r0.w
mul r0.w, r0.w, r4.x
add r0.w, r0.w, r2.w
div r0.w, l(1.000000), r0.w  // r0.w <- <Attenuate return value>

#line 46 "F:\MyRepo\DirectXRenderer\Sandbox\asset\shader\PhongDifSpc_PS.hlsl"
nop 
mov r4.xyz, cb0[2].xyzx
mov r2.w, cb0[2].w

#line 30 "F:\MyRepo\DirectXRenderer\Sandbox\asset\shader\Common\ShaderOps.hlsli"
mul r4.xyz, r2.wwww, r4.xyzx
mul r4.xyz, r0.wwww, r4.xyzx
dp3 r2.x, r2.xyzx, r0.xyzx
max r2.x, r2.x, l(0.000000)
mul r2.xyz, r2.xxxx, r4.xyzx  // r2.x <- <Diffuse return value>.x; r2.y <- <Diffuse return value>.y; r2.z <- <Diffuse return value>.z

#line 46 "F:\MyRepo\DirectXRenderer\Sandbox\asset\shader\PhongDifSpc_PS.hlsl"
mov r2.xyz, r2.xyzx  // r2.x <- diffuse.x; r2.y <- diffuse.y; r2.z <- diffuse.z

#line 48
nop 
mul r3.xyz, r3.xyzx, cb0[2].xyzx
mov r2.w, cb1[1].w

#line 43 "F:\MyRepo\DirectXRenderer\Sandbox\asset\shader\Common\ShaderOps.hlsli"
dp3 r3.w, r1.xyzx, r0.xyzx
mul r0.xyz, r0.xyzx, r3.wwww  // r0.x <- w.x; r0.y <- w.y; r0.z <- w.z

#line 44
mul r0.xyz, r0.xyzx, l(2.000000, 2.000000, 2.000000, 0.000000)
mov r1.xyz, -r1.xyzx
add r0.xyz, r0.xyzx, r1.xyzx
dp3 r1.x, r0.xyzx, r0.xyzx
rsq r1.x, r1.x
mul r0.xyz, r0.xyzx, r1.xxxx  // r0.x <- r.x; r0.y <- r.y; r0.z <- r.z

#line 46
dp3 r1.x, v0.xyzx, v0.xyzx
rsq r1.x, r1.x
mul r1.xyz, r1.xxxx, v0.xyzx  // r1.x <- viewCamToFrag.x; r1.y <- viewCamToFrag.y; r1.z <- viewCamToFrag.z

#line 49
mul r3.xyz, r0.wwww, r3.xyzx
mul r3.xyz, r2.wwww, r3.xyzx
mov r0.xyz, -r0.xyzx
dp3 r0.x, r0.xyzx, r1.xyzx
max r0.x, r0.x, l(0.000000)
log r0.x, r0.x
mul r0.x, r0.x, r1.w
exp r0.x, r0.x
mul r0.xyz, r0.xxxx, r3.xyzx  // r0.x <- <Speculate return value>.x; r0.y <- <Speculate return value>.y; r0.z <- <Speculate return value>.z

#line 48 "F:\MyRepo\DirectXRenderer\Sandbox\asset\shader\PhongDifSpc_PS.hlsl"
mov r0.xyz, r0.xyzx  // r0.x <- specularReflected.x; r0.y <- specularReflected.y; r0.z <- specularReflected.z

#line 53
add r1.xyz, r2.xyzx, cb0[1].xyzx
sample_indexable(texture2d)(float,float,float,float) r2.xyz, v2.xyxx, t0.xyzw, s0
mul r1.xyz, r1.xyzx, r2.xyzx
add r0.xyz, r0.xyzx, r1.xyzx
max r0.xyz, r0.xyzx, l(0.000000, 0.000000, 0.000000, 0.000000)
min o0.xyz, r0.xyzx, l(1.000000, 1.000000, 1.000000, 0.000000)
mov o0.w, l(1.000000)
ret 
// Approximately 75 instruction slots used
