//
// Generated by Microsoft (R) HLSL Shader Compiler 10.1
//
//
// Buffer Definitions: 
//
// cbuffer LightCBuf
// {
//
//   float3 lightPos;                   // Offset:    0 Size:    12
//   float3 ambient;                    // Offset:   16 Size:    12
//   float3 diffuseColor;               // Offset:   32 Size:    12
//   float diffuseIntensity;            // Offset:   44 Size:     4
//   float attConst;                    // Offset:   48 Size:     4
//   float attLin;                      // Offset:   52 Size:     4
//   float attQuad;                     // Offset:   56 Size:     4
//
// }
//
// cbuffer ObjectCBuf
// {
//
//   float3 materialColor;              // Offset:    0 Size:    12
//
// }
//
//
// Resource Bindings:
//
// Name                                 Type  Format         Dim      HLSL Bind  Count
// ------------------------------ ---------- ------- ----------- -------------- ------
// LightCBuf                         cbuffer      NA          NA            cb0      1 
// ObjectCBuf                        cbuffer      NA          NA            cb1      1 
//
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// Position                 0   xyz         0     NONE   float   xyz 
// Normal                   0   xyz         1     NONE   float   xyz 
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_Target                0   xyzw        0   TARGET   float   xyzw
//
ps_5_0
dcl_globalFlags refactoringAllowed | skipOptimization
dcl_constantbuffer CB0[4], immediateIndexed
dcl_constantbuffer CB1[1], immediateIndexed
dcl_input_ps linear v0.xyz
dcl_input_ps linear v1.xyz
dcl_output o0.xyzw
dcl_temps 2
//
// Initial variable locations:
//   v0.x <- worldPos.x; v0.y <- worldPos.y; v0.z <- worldPos.z; 
//   v1.x <- n.x; v1.y <- n.y; v1.z <- n.z; 
//   o0.x <- <main return value>.x; o0.y <- <main return value>.y; o0.z <- <main return value>.z; o0.w <- <main return value>.w
//
#line 20 "F:\MyRepo\DirectXRenderer\Sandbox\asset\shader\Phong_ps.hlsl"
mov r0.xyz, -v0.xyzx
add r0.xyz, r0.xyzx, cb0[0].xyzx  // r0.x <- vToL.x; r0.y <- vToL.y; r0.z <- vToL.z

#line 21
dp3 r0.w, r0.xyzx, r0.xyzx
sqrt r0.w, r0.w  // r0.w <- distToL

#line 22
div r0.xyz, r0.xyzx, r0.wwww  // r0.x <- dirToL.x; r0.y <- dirToL.y; r0.z <- dirToL.z

#line 24
mul r1.x, r0.w, cb0[3].y
add r1.x, r1.x, cb0[3].x
mul r0.w, r0.w, r0.w
mul r0.w, r0.w, cb0[3].z
add r0.w, r0.w, r1.x
div r0.w, l(1.000000), r0.w  // r0.w <- att

#line 26
mul r1.xyz, cb0[2].wwww, cb0[2].xyzx
mul r1.xyz, r0.wwww, r1.xyzx
dp3 r0.x, r0.xyzx, v1.xyzx
max r0.x, r0.x, l(0.000000)
mul r0.xyz, r0.xxxx, r1.xyzx  // r0.x <- diffuse.x; r0.y <- diffuse.y; r0.z <- diffuse.z

#line 28
add r0.xyz, r0.xyzx, cb0[1].xyzx
mul r0.xyz, r0.xyzx, cb1[0].xyzx
max r0.xyz, r0.xyzx, l(0.000000, 0.000000, 0.000000, 0.000000)
min o0.xyz, r0.xyzx, l(1.000000, 1.000000, 1.000000, 0.000000)
mov o0.w, l(1.000000)
ret 
// Approximately 22 instruction slots used
