//
// Generated by Microsoft (R) HLSL Shader Compiler 10.1
//
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// Position                 0   xyz         0     NONE   float   xyz 
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_TARGET                0   xyzw        0   TARGET   float   xyzw
//
ps_5_0
dcl_globalFlags refactoringAllowed
dcl_input_ps linear v0.xyz
dcl_output o0.xyzw
dcl_temps 1
dp3 r0.x, v0.xyzx, v0.xyzx
sqrt r0.x, r0.x
mad o0.xyzw, r0.xxxx, l(0.010000, 0.010000, 0.010000, 0.010000), l(0.005000, 0.005000, 0.005000, 0.005000)
ret 
// Approximately 4 instruction slots used
